return {
  "github/copilot.vim",
  init = function() end,
  config = function()
    vim.keymap.set("i", "<C-e>", [[copilot#Accept("\<CR>")]], {
      silent = true,
      expr = true,
      script = true,
      replace_keycodes = false,
    })
    vim.g.copilot_filetypes = {
      ["vim"] = true,
      ["viml"] = true,
      ["sh"] = true,
      ["bash"] = true,
      ["zsh"] = true,
      ["fish"] = true,
      ["html"] = true,
      ["css"] = true,
      ["scss"] = true,
      ["sass"] = true,
      ["less"] = true,
      ["json"] = true,
      ["yaml"] = true,
      ["toml"] = true,
      ["xml"] = true,
      ["php"] = true,
      ["ruby"] = true,
      ["perl"] = true,
      ["java"] = true,
      ["javascript"] = true,
      ["typescript"] = true,
      ["lua"] = true,
      ["rust"] = true,
      ["c"] = true,
      ["c#"] = true,
      ["c++"] = true,
      ["go"] = true,
      ["python"] = true,
      ["markdown"] = true,
    }
  end,
}
